# Generated by Django 3.2.4 on 2021-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_content', models.TextField()),
                ('sub_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
