# Generated by Django 3.2.4 on 2021-06-17 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_auto_20210617_2002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sub_Board',
        ),
    ]
