# Generated by Django 3.2.4 on 2021-06-17 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_delete_sub_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board_app.board')),
            ],
        ),
    ]
