# Generated by Django 3.2.4 on 2021-06-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0005_sub_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_board',
            old_name='board_id',
            new_name='board',
        ),
    ]
